id: 2af6a1b61a214b3086d29b8319d4c3ed
title: Toh_163-Questions_of_Ratnaj%C4%81lin-v2
type: translation
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-059-006
  eft-text-version: 1.0.1 2020
